# -*- coding: utf-8 -*-
"""PythonExercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOCSaQyUiv8lLT5U1yCLSw31y9xVVM4K
"""

a = 'hello world'
print(a[-1])

a = 'hellow world'
print(a.upper())

a = 'HELLOW WORLD'
print(a.lower())

a = 'Hey Hello. Is this actually work?'
print(a.split())

nm = 'Junayed'
print('My name is {}'.format(nm))

nm = input()
print('Your name is {}'.format(nm))

nm =  input()
print(f"My name is {nm}")

list1 = [1,2,3,4,6,7,3,2]
len(list1)

list1 = ['Junayed','Pc-A','201-15-3294']
print(list1[1])
print(type(list1))
len(list1)

print(10)

print("This is string")

print("Up\nDown")

type(True)

type(False)

type(1.5)

a= [1,2,3]
b = 'Junayed'
for i in b:

    for j in a:
        print(i,j)

x = 0
while x<10:
  print(x)
  x+=1

x= 10
while x>0:
  print(x)
  x-=1

x= 10
while x>0:
  if x==4:
    break
  print(x)
  x-=1

def name(a,b):
  c = a+b
  return b
  a=name(5,6)
  print(c)

a = int(input())
b = int(input())
if a>b:
  print("Daffodil International University")

i = int (input())
if 6>i:
  print(i)

i = 1
while i < 6:
  print(i)
  i+=1

fruits = ['Banana','Mango','Apple']
for x in fruits:
  print(x)

i = 3
while i<6:
  print(i)
  if i == 3:
    break
    i += 1

from ast import If
print("Enter your age: ")
age = int(input())

if age > 70:
  print("You are dead!")
elif age > 18:
  print("So,you can swim")

elif age == 18:
  print("Your age is equal to ",age)
  print("So,you can swim")

else:
  print("Your age is : ",age)
  print("So,you can't swim")

from ast import If
x = int(input("Enter any number to check odd or even :"))

if x%2 == 0:
  print("it is even")
else:
  print("it is odd")

x = int (input("X = "))
y = int (input("Y = "))

if x > y:
  print("x is larger then y")
else:
  print("X is smaller then y")

def find_len(list1):
    length = len(list1)
    list1.sort()
    print("Largest element is:", list1[length-1])
    print("Smallest element is:", list1[0])
    print("Second Largest element is:", list1[length-2])
    print("Second Smallest element is:", list1[1])


list1=[12, 1, 2, 41, 31, 10, 8, 6, 4]
Largest = find_len(list1)

num = 29
flag = False

if num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            flag = True
            break
if flag:
    print(num, "is not a prime number")
else:
    print(num, "is a prime number")

year = 2000

if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

else:
    print("{0} is not a leap year".format(year))

def check(string):
    string = string.lower()

    vowels = set("aeiou")

    s = set({})

    for char in string:

        if char in vowels:
            s.add(char)
        else:
            pass

    if len(s) == len(vowels):
        print("Accepted")
    else:
        print("Not Accepted")

if __name__ == "__main__":
    string = "ABeeIghiObhkUul"
    check(string)

employeid=int(input("Input the Employees ID: "))

work_hour=int(input("Input total working (Hrs/mounth): "))

payment=int(input("Salary(per/Hr): "))

total=float(work_hour*payment)

print("\nEmployee ID:",employeid)

print("Total salary of a particular month: %0.2f Tk "%total)

value = [1,2,3,4,5,6,7,8,9]
value2 =[1,2,3]
for item in value:
  if item == 5:
    continue
  print("break")
  for item2 in value2:
    print(item,item2)